s = input("Enter a string: ")

print("Lower:", s.lower())
print("Upper:", s.upper())
print("Title:", s.title())
print("Capitalize:", s.capitalize())
print("Swapcase:", s.swapcase())
print("Replace (a->@):", s.replace("a", "@"))
print("Split:", s.split())
print("Find 'a':", s.find("a"))
print("Count of 'a':", s.count("a"))
print("Starts with 'H':", s.startswith("H"))
print("Ends with 'd':", s.endswith("d"))
print("Length:", len(s))
